#pragma once

#ifndef CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 20202021
#endif

#ifndef CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 3840
#endif

#define CHIP_CONFIG_SECURITY_TEST_MODE 0

// Test VID/PID are for development only.
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Salu Workshop"
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF1
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "Hob2Hood"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID 0x8006
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_REVISION 1

#define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION 1
#define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING "BL702"

#ifndef CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "0.1"
#endif

#ifndef CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION 1
#endif

#define CHIP_DEVICE_CONFIG_TEST_SERIAL_NUMBER "XT-ZB2-HOOD-01"
#define CHIP_DEVICE_CONFIG_EVENT_LOGGING_UTC_TIMESTAMPS 1
#define CHIP_DEVICE_CONFIG_EVENT_LOGGING_DEBUG_BUFFER_SIZE 128
#define CHIP_DEVICE_CONFIG_ENABLE_EXTENDED_DISCOVERY 1
#define CHIP_BLE_DEVICE_NAME "Hob2Hood"

// XT-ZB2 has only the BL702 internal RAM.  Keep the platform's known-working
// Matter table sizes; reducing these tables can corrupt transport state in
// this older Bouffalo Matter port during Server initialization.
#define CHIP_CONFIG_MAX_FABRICS 2
#define CHIP_IM_MAX_NUM_COMMAND_HANDLER 1
#define CHIP_IM_MAX_NUM_WRITE_HANDLER 1
#define CHIP_IM_MAX_NUM_WRITE_CLIENT 1
#define CHIP_IM_MAX_NUM_TIMED_HANDLER 2
