name: Build firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./scripts/build.sh
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: hob2hood-bl702
          path: |
            out/hob2hood/chip-bl702-hood-example.bin
            out/hob2hood/chip-bl702-hood-example.out.map
            config/partition_cfg_2M.toml

